// ROOT MUTATIONS
export const SET_APP_SERVICE = 'SET_APP_SERVICE'
export const FETCHED_STATUS = 'FETCHED_STATUS'

// WEATHER MUTATIONS
export const CONFIRM_GEOLOCATION_SUPPORT = 'CONFIRM_GEOLOCATION_SUPPORT'
export const NO_GEOLOCATION_SUPPORT = 'NO_GEOLOCATION_SUPPORT'
export const HANDLE_GEOLOCATION_SUCCESS = 'HANDLE_GEOLOCATION_SUCCESS'
export const HANDLE_GEOLOCATION_ERROR = 'HANDLE_GEOLOCATION_ERROR'
export const SET_USER_POSITION = 'SET_USER_POSITION'
export const SET_USER_LOCATION = 'SET_USER_LOCATION'

export const SET_CURRENT_ERROR = 'SET_CURRENT_ERROR'
export const SET_STATE_ON_PROP = 'SET_STATE_ON_PROP'
export const BIND_STORE_PROPERTY = 'BIND_STORE_PROPERTY'
